### ISSUE TITLE
рефакторинг

### ISSUE THREAD

**Issue by pecourses** [Jaykob2447/Js_learn#2]
https://github.com/Jaykob2447/Js_learn/blob/f4ddc5d950888ed56425e1db52113dcfae31dc78/les_css_1/index.html#L12-L25
- тут семантично не потрібен поділ на секції. За великим рахунком, якщо можна обійтися без додаткових обгорток, то і розмітка буде легше читатися, і стилі.
```html
    <header class="sec_head">
      <div class="bg_image"></div>
      <h1>Welcome to Acme Web Solutions</h1>
      <p>
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Adipisci eum
        error earum soluta voluptatum nisi laboriosam eos saepe asperiores
        dolorum.
      </p>
      <a href="#"
        >Read More
        <div class="good_border"></div
      ></a>
    </header>
``` 
```css
.bg_image {
  background-image: url(../image/img1.png);
  background-color: #333;
  background-repeat: no-repeat;
  background-size: cover;
  position: absolute;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  opacity: 0.9;
  z-index: -5;
}

.sec_head {
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-direction: column;
  padding: 0% 15%;
  min-height: 35em;
  position: relative;
}
```
