### ISSUE TITLE
експеримент

### ISSUE THREAD

**Issue by pecourses** [Jaykob2447/Js_learn#4]
https://github.com/Jaykob2447/Js_learn/blob/f4ddc5d950888ed56425e1db52113dcfae31dc78/les_css_1/css/style.css#L60
- в ідеалі не підбирати позицію для "мігалки" (тим більше зараз при зміні ширини воно з'їжджає), а "приколотити"до посилання:
```css
.good_border {
  filter: blur(45px);
  border-radius: 15px;
  /* content: ""; не треба - це не before/after */ 
  /* width: 179px; - жорстко не фіксуємо розміри, а прикріпляємо краї*/
  /* height: 82px; */
  position: absolute;
  z-index: -1;
  /* top: 389px; - тепер не підбираємо, а прикріпляємо до країв посилання*/
  /* left: 650px; */
  /* left: 50%; */
  /* transform: translateX(-50%); */
  left: 0; /* прибиваємо до країв посилання 💡*/ 
  right: 0;
  top: 0;
  bottom: 0;
  animation: 0.6s linear none rgb_cykle;
  animation-iteration-count: infinite;
}
``` 
ОБОВʼЯЗКОВО задати батьківському посиланню 💡`position: relative;`, щоб приколотити саме до нього. Ми будемо звертати на подібні ситуації увагу при вивченні позиціонування.
